# Generated by Django 5.2.9 on 2025-12-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_count', models.PositiveIntegerField()),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('vegetarian', 'Vegetarian Dinner'), ('seafood', 'Seafood Dinner'), ('protein', 'Protein Dinner'), ('other', 'Other')], default='other', max_length=20)),
                ('last_used', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=100)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.mealplanweek')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('pantry', 'Pantry'), ('produce', 'Produce'), ('protein', 'Protein'), ('frozen', 'Frozen'), ('dairy', 'Dairy')], max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planner.recipe')),
            ],
        ),
    ]
