# Generated by Django 5.2.9 on 2025-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
