# Generated by Django 5.2.9 on 2025-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_plannedmeal_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanweek',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
