# Generated by Django 5.2.9 on 2025-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_mealplanweek_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_note',
            field=models.CharField(blank=True, help_text="Skinnytaste book + page, or 'Online'.", max_length=200),
        ),
    ]
